# -*- mode: ruby -*-
# vi: set ft=ruby :

#https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_with_python_environment_setup.htm

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu16.04"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python-pip
    # libraries and packages generally used in performing various machine learning tasks
    pip install numpy
    pip install matplotlib
    pip install pandas
    pip install seaborn
    pip install scikit-learn
    pip install scipy
  SHELL
end
